[build]
target = "wasm32-unknown-unknown"

[target.wasm32-unknown-unknown]
rustflags = [
    "-C", "link-arg=--no-entry",
    "-C", "link-arg=--export-dynamic",
    "-C", "link-arg=-zstack-size=1048576",
]
